### ISSUE TITLE
Dockerfile setting 777 permissions on storage folder

### ISSUE THREAD

**Issue by reneManqueros** [WendellAdriel/laravel-exa#10]
Maybe the permissions can be reduced to something less dangerous?

https://github.com/WendellAdriel/laravel-exa/blob/3c79daa149a6bf355d0264f8800ad63553925d88/docker/app/Dockerfile#L52

**Comment by WendellAdriel** [comment]
Oh, that's a really good point
I forgot to update that 😅 
Thanks for pointing that out, I'll update it and release a new version

**Comment by WendellAdriel** [comment]
I'm going to set this as 775 since it's the default for the storage folder

**Comment by WendellAdriel** [comment]
Fixed in v1.7.2
