### ISSUE TITLE
API Documentation using Swagger

### ISSUE THREAD

**Issue by msoares94** [WendellAdriel/laravel-exa#7]
The documentation of an API is like a road code manual for a driver.
It guides users of the application, allowing developers to understand how the application works without having to read the entire implementation.

Would it be possible to provide documentation for the API using Swagger?

**Comment by WendellAdriel** [comment]
That's in the roadmap, TBH is the next thing that I need to release for ExA.
If everything goes as planned, between this and the next week I can release a version with Swagger integrated already.

**Comment by WendellAdriel** [comment]
This is now available on v1.5.0
